### ISSUE TITLE
train_tff.py accuracy and loss in OrderedDict

### ISSUE THREAD

**Issue by KavishBhatia** [CS-savvy/experiment_with_tf_federated#4]
In the file train_tff.py on line 131 and 133
```
    tff_train_acc.append(float(tff_metrics.sparse_categorical_accuracy))
    tff_train_loss.append(float(tff_metrics.loss))
```
instead it should be 
```
   tff_train_acc.append(float(tff_metrics['train']['sparse_categorical_accuracy']))
   tff_train_loss.append(float(tff_metrics['train']['loss']))
```

**Comment by CS-savvy** [comment]
@KavishBhatia This depends on tf-federated or tensorflow version. May i know which version you are using?

**Comment by KavishBhatia** [comment]
> @KavishBhatia This depends on tf-federated or tensorflow version. May i know which version you are using?

tensorflow == 2.2.0
tensorflow-federated ==0.16.0

**Comment by CS-savvy** [comment]
@KavishBhatia i have tested this code at
```
tensorflow==2.1.0
tensorflow-federated==0.13.1
```
as mentioned in [requirement.txt](https://github.com/CS-savvy/experiment_with_tf_federated/blob/master/requirements.txt)
I will update the code based on latest version. Thanks for pointing out :)
